version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-stretch-browsers
        auth:
          username: khaledelgendy
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t khaledelgendy/capstoneproject:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push haledelgendy/capstoneproject:$TAG
