version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: khaledelgendy
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t khaledelgendy/capstoneproject:$TAG .
          docker login -u khaledelgendy -p $DOCKERHUB_PASSWORD
          docker push khaledelgendy/capstoneproject:$TAG
